language: java
addons:
  sonarcloud:
    organization: "theosegard"
    token: "TheoSegard_ipi-java-350-ex"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=TheoSegard_ipi-java-350-ex